### ISSUE TITLE
Could not connect to repository

### ISSUE THREAD

**Issue by xalaros** [mhdzumair/MediaFusion#346]
Kodi 21.1
Install from zip file "MediaFusion Repository" appears "Could not connect to repository".

**Comment by mhdzumair** [comment]
Hi @xalaros that is still on testing. i created for testing on release pipeline. However the release pipeline didnt create the github release page. will fix it.

**Comment by OldManJax** [comment]
It was a small error in the code that has been fixed and is working now.

**Comment by nithin2027** [comment]
@OldManJax still getting the same error "Could not connect to the repository"

**Comment by OldManJax** [comment]
Try going to your add-ons browser, install from repo, then activate the context menu on the mediafusion repo and choose Check for updates. That might force it to recognize the change. You may have to uninstall it, reboot Kodi then install it again.

**Comment by IG2022** [comment]
I'm also having the same issue and I'm unable to access the repository and download the addon.

**Comment by IG2022** [comment]
Working for me now!

**Comment by xalaros** [comment]
The same error "Could not connect to repository" with MediaFusion Repository v4.1.5

**Comment by nithin2027** [comment]
@mhdzumair for macos kodi it is connecting now but for android firestick TV it shows Could not connect to repository

**Comment by mhdzumair** [comment]
I have added video zip entry into the home page so you can directly download the video addon from that. 

Add Mediafusion source -> Install from zip file -> you will see both repository and video zip. Choose video zip to install mediafusion

**Comment by barrowman** [comment]
Getting the "Could not connect to repository" as everyone else is.

**Comment by akistigas** [comment]
Hey there, still getting the error "Could not connect to the repository". Kodi 21.1

**Comment by Almo7aya** [comment]
I'm getting this error message
![image](https://github.com/user-attachments/assets/ca485e6d-3bd0-4cc6-ba32-dbd982f643ba)

**Comment by CowcudIsaTwin** [comment]
For anyone getting the ‘could not connect to repository’ message try re-starting kodi after installing from zip then try install from repository. That just worked for me.

**Comment by mhdzumair** [comment]
I just freshly set up the kodi from scratch on Linux. Apparently, you just need to restart the kodi after installing the repository, 

just updated the README with this guide, 

#### Method 1: Install via Repository (Recommended)
1. Launch Kodi
2. Go to Settings (⚙️ gear icon) → File manager
3. Click on "Add source"
4. In the "Add file source" dialog, click `<None>` and enter exactly:
   ```
   https://mhdzumair.github.io/MediaFusion
   ```
5. In the "Enter a name for this media source" field, enter `MediaFusion` and click "OK"
6. Go back to Kodi home screen
7. Click Add-ons
8. Click the Add-on browser (box icon) 
9. Click "Install from zip file"
10. Click "MediaFusion"
11. Select the repository zip file (e.g., `repository.mediafusion-4.1.1.zip`)
12. Wait for the "MediaFusion Repository add-on installed" notification
13. Click "Install from repository"
14. Select "MediaFusion Repository." If it says "Could not connect to repository", close Kodi and open it again and go to add-ons and start from step 13.
15. Go to "Video add-ons"
16. Select "MediaFusion"
17. Click "Install"
18. Configure the add-on by going to Add-ons → My add-ons → Video add-ons → MediaFusion → Configure
